
// v2_2 board is functionally identical to v2_1, so reuse the code
#include "../board_v2_1/board.hpp"

// change board name
#undef BOARD_NAME
#undef BOARD_REVISION
#define BOARD_NAME "NanoVNA V2_3"
#define BOARD_REVISION (3)

#ifdef EXPERIMENTAL_NPERIODS
#define BOARD_MEASUREMENT_NPERIODS_NORMAL  		10
#define BOARD_MEASUREMENT_NPERIODS_CALIBRATING	23
#define BOARD_MEASUREMENT_ECAL_INTERVAL 		20
#define BOARD_MEASUREMENT_NWAIT_SWITCH 			 4
#define BOARD_MEASUREMENT_MIN_CALIBRATION_AVG	20
#define BOARD_MEASUREMENT_MAX_CALIBRATION_AVG  255
#define BOARD_MEASUREMENT_FIRST_POINT_WAIT	   128
#else
#define BOARD_MEASUREMENT_NPERIODS_NORMAL		20
#define BOARD_MEASUREMENT_NPERIODS_CALIBRATING	45
#define BOARD_MEASUREMENT_ECAL_INTERVAL			 8
#define BOARD_MEASUREMENT_NWAIT_SWITCH			 5
#define BOARD_MEASUREMENT_MIN_CALIBRATION_AVG	 4
#define BOARD_MEASUREMENT_MAX_CALIBRATION_AVG  255
#define BOARD_MEASUREMENT_FIRST_POINT_WAIT	   128
#endif